1)

In [6]:
import numpy as np

# Definindo as matrizes A e B
x = np.array([[1, 1],
              [1, 3],
              [1, 6],
              [1, 9],
              [1, 8]])


Xtransposto = np.array([[1, 1, 1, 1, 1],
                        [1, 3, 6, 9, 8]])

Ynum = np.array([[1.25],
              [7],
              [2.7],
              [3.2],
              [5.5]])
# Multiplicando as matrizes A e Xtransposto
C = Xtransposto @ x
C_inv = np.linalg.inv(C)

d = C_inv @ Xtransposto

res = d @ Ynum
# ExiXtranspostoindo o resultado
print("Resultado da multiplicação de Xtransposto e X:")
print(C)

print("\nMatriz inversa de Xtransposto * X:")
print(C_inv)

print("\n(Matriz inversa de Xtransposto * X) * Xtransposto:")
print(d)

print("\n W:")
print(res)

Resultado da multiplicação de Xtransposto e X:
[[  5  27]
 [ 27 191]]

Matriz inversa de Xtransposto * X:
[[ 0.84513274 -0.11946903]
 [-0.11946903  0.02212389]]

(Matriz inversa de Xtransposto * X) * Xtransposto:
[[ 0.72566372  0.48672566  0.12831858 -0.2300885  -0.11061947]
 [-0.09734513 -0.05309735  0.01327434  0.07964602  0.05752212]]

 W:
[[3.3159292 ]
 [0.11371681]]


2)

In [3]:
# Definindo as matrizes A e B
X = np.array([[1, 1],
              [1, 3],
              [1, 6],
              [1, 9],
              [1, 8]])

Xtransposto = np.array([[1, 1, 1, 1, 1],
                        [1, 3, 6, 9, 8]])

Ynum = np.array([[1.25],
              [7],
              [2.7],
              [3.2],
              [5.5]])

I = np.array([[1, 0],
              [0, 1]])

lamb = 1
# Multiplicando as matrizes A e Xtransposto
C = Xtransposto @ X

CeI = C + (lamb * I)

CeI_inv = np.linalg.inv(CeI)

d = CeI_inv @ Xtransposto

res = d @ Ynum
# ExiXtranspostoindo o resultado
print("Resultado da multiplicação de Xtransposto e X:")
print(C)

print("\n(Xtransposto * X) + lambda*I:")
print(CeI)

print("\nMatriz inversa de (Xtransposto * X) + lambda*I:")
print(CeI_inv)

print("\n(Matriz inversa de (Xtransposto * X) + lambda*I) * Xtransposto:")
print(d)

print("\n W:")
print(res)

Resultado da multiplicação de Xtransposto e X:
[[  5  27]
 [ 27 191]]

(Xtransposto * X) + lambda*I:
[[  6  27]
 [ 27 192]]

Matriz inversa de (Xtransposto * X) + lambda*I:
[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]

(Matriz inversa de (Xtransposto * X) + lambda*I) * Xtransposto:
[[ 0.39007092  0.26241135  0.07092199 -0.12056738 -0.05673759]
 [-0.04964539 -0.0212766   0.0212766   0.06382979  0.04964539]]

 W:
[[1.81808511]
 [0.32375887]]


3)

In [21]:
# Definindo as matrizes A e B

x_train = np.array([
    [1, 1],
    [1, 3],
    [1, 6],
    [1, 9],
    [1, 8]
])
y_train_real = np.array([[1.25], [7.0], [2.7], [3.2], [5.5]])


x_test = np.array([
    [1, 4],
    [1, 2],
    [1, 5]
])
y_test_real = np.array([[0.7], [1.1], [2.2]])

w_ols = np.array([[3.31593], [0.11372]])
w_ridge = np.array([[1.81809], [0.32376]])

res_test_ols = x_test @ w_ols
res_test_ridge = x_test @ w_ridge

res_train_ols = x_train @ w_ols
res_train_ridge = x_train @ w_ridge


#print("Resultado res_test_ols:")
#print(res_test_ols)
print("\n Resultado res_test_ridge :")
print(res_test_ridge)
print("\n Resultado res_train_ols:")
print(res_train_ols)
print("\n Resultado res_train_ridge:")
print(res_train_ridge)

def rmse(y_real, y_pred):
    return np.sqrt(np.mean((y_real - y_pred) ** 2))

# Calculando o RMSE
rmse_train_ols = rmse(y_train_real, res_train_ols)
rmse_test_ols = rmse(y_test_real, res_test_ols)

rmse_train_ridge = rmse(y_train_real, res_train_ridge)
rmse_test_ridge = rmse(y_test_real, res_test_ridge)

print("\nRMSE train OLS:", rmse_train_ols)
print("\nRMSE test OLS: ", rmse_test_ols)
print("\nRMSE train Ridge: ", rmse_train_ridge)
print("\nRMSE test Ridge: ", rmse_test_ridge)




 Resultado res_test_ridge :
[[3.11313]
 [2.46561]
 [3.43689]]

 Resultado res_train_ols:
[[3.42965]
 [3.65709]
 [3.99825]
 [4.33941]
 [4.22569]]

 Resultado res_train_ridge:
[[2.14185]
 [2.78937]
 [3.76065]
 [4.73193]
 [4.40817]]

RMSE train OLS: 2.026499226612238

RMSE test OLS:  2.4656015042919375

RMSE train Ridge:  2.15354043916988

RMSE test Ridge:  1.752900828255837
