1)

In [2]:
import numpy as np

# Definindo as matrizes A e B
x = np.array([[1, 1],
              [1, 3],
              [1, 6],
              [1, 9],
              [1, 8]])


Xtransposto = np.array([[1, 1, 1, 1, 1],
                        [1, 3, 6, 9, 8]])

Ynum = np.array([[1.25],
              [7],
              [2.7],
              [3.2],
              [5.5]])
# Multiplicando as matrizes A e Xtransposto
C = Xtransposto @ x
C_inv = np.linalg.inv(C)

d = C_inv @ Xtransposto

res = d @ Ynum
# ExiXtranspostoindo o resultado
print("Resultado da multiplicação de Xtransposto e X:")
print(C)

print("\nMatriz inversa de Xtransposto * X:")
print(C_inv)

print("\n(Matriz inversa de Xtransposto * X) * Xtransposto:")
print(d)

print("\n W:")
print(res)

Resultado da multiplicação de Xtransposto e X:
[[  5  27]
 [ 27 191]]

Matriz inversa de Xtransposto * X:
[[ 0.84513274 -0.11946903]
 [-0.11946903  0.02212389]]

(Matriz inversa de Xtransposto * X) * Xtransposto:
[[ 0.72566372  0.48672566  0.12831858 -0.2300885  -0.11061947]
 [-0.09734513 -0.05309735  0.01327434  0.07964602  0.05752212]]

 W:
[[3.3159292 ]
 [0.11371681]]


2)

In [3]:
# Definindo as matrizes A e B
X = np.array([[1, 1],
              [1, 3],
              [1, 6],
              [1, 9],
              [1, 8]])

Xtransposto = np.array([[1, 1, 1, 1, 1],
                        [1, 3, 6, 9, 8]])

Ynum = np.array([[1.25],
              [7],
              [2.7],
              [3.2],
              [5.5]])

I = np.array([[1, 0],
              [0, 1]])

lamb = 1
# Multiplicando as matrizes A e Xtransposto
C = Xtransposto @ X

CeI = C + (lamb * I)

CeI_inv = np.linalg.inv(CeI)

d = CeI_inv @ Xtransposto

res = d @ Ynum
# ExiXtranspostoindo o resultado
print("Resultado da multiplicação de Xtransposto e X:")
print(C)

print("\n(Xtransposto * X) + lambda*I:")
print(CeI)

print("\nMatriz inversa de (Xtransposto * X) + lambda*I:")
print(CeI_inv)

print("\n(Matriz inversa de (Xtransposto * X) + lambda*I) * Xtransposto:")
print(d)

print("\n W:")
print(res)

Resultado da multiplicação de Xtransposto e X:
[[  5  27]
 [ 27 191]]

(Xtransposto * X) + lambda*I:
[[  6  27]
 [ 27 192]]

Matriz inversa de (Xtransposto * X) + lambda*I:
[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]

(Matriz inversa de (Xtransposto * X) + lambda*I) * Xtransposto:
[[ 0.39007092  0.26241135  0.07092199 -0.12056738 -0.05673759]
 [-0.04964539 -0.0212766   0.0212766   0.06382979  0.04964539]]

 W:
[[1.81808511]
 [0.32375887]]


3)

In [4]:
# Definindo as matrizes A e B
x = np.array([#[1, 1],
              #[1, 3],
              #[1, 6],
              #[1, 9],
              #[1, 8],
              [1, 4],
              [1, 2],
              [1, 5]])

Y1 = np.array([[3.316],
               [0.114]])

Y2 = np.array([[1.818],
               [0.324]])

res1 = x @ Y1
res2 = x @ Y2


print("Resultado1:")
print(res1)
print("\n Resultado2:")
print(res2)

def rmse(y_real, y_pred):
    return np.sqrt(np.mean((y_real - y_pred) ** 2))

y_real = np.array([#[1.25], [7], [2.7], [3.2], [5.5],
                     [0.7], [1.1], [2.2]]) 
y_pred_1 = res1 
y_pred_2 = res2 

# Calculando o RMSE
resultado_rmse_1 = rmse(y_real, y_pred_1)
resultado_rmse_2 = rmse(y_real, y_pred_2)

print("\nRMSE1:")
print(resultado_rmse_1)
print("\nRMSE2:")
print(resultado_rmse_2)

Resultado1:
[[3.772]
 [3.544]
 [3.886]]

 Resultado2:
[[3.114]
 [2.466]
 [3.438]]

RMSE1:
2.46663846830729

RMSE2:
1.7536624532674467
