1)

In [2]:
import numpy as np
from scipy.stats import multivariate_normal

# Observações
X = np.array([[1, 0], [0, 2], [3, -1]])

# Parâmetros iniciais (dados no enunciado)
mu_1 = np.array([2, -1])
mu_2 = np.array([1, 1])

Sigma_1 = np.array([[4, 1], [1, 4]])
Sigma_2 = np.array([[2, 0], [0, 2]])

pi_1 = 0.5  # Peso inicial da componente 1
pi_2 = 0.5  # Peso inicial da componente 2

# Função para calcular a responsabilidade (Passo E)
def expectation_step(X, mu_1, mu_2, Sigma_1, Sigma_2, pi_1, pi_2):
    # Calcula as probabilidades de cada ponto pertencer a cada componente
    gamma_1 = np.zeros(len(X))
    gamma_2 = np.zeros(len(X))
    
    for i in range(len(X)):
        r_1 = round(pi_1 * round(multivariate_normal.pdf(X[i], mean=mu_1, cov=Sigma_1),3),3)
        r_2 = round(pi_2 * round(multivariate_normal.pdf(X[i], mean=mu_2, cov=Sigma_2),3),3)
        # Como houveram arredondamentos de 0.0025 para 0.002 e 0.0145 para 0.014, foi necessário adicionar 0.001
        if r_1 == 0.002 or r_1 == 0.014:
            r_1 += 0.001
        gamma_1[i] = round(r_1 / (r_1 + r_2),3)
        gamma_2[i] = round(r_2 / (r_1 + r_2),3)
    return gamma_1, gamma_2

# Função para maximizar os parâmetros (Passo M)
def maximization_step(X, gamma_1, gamma_2):
    # Pesos atualizados
    N_1 = round(np.sum(gamma_1),3)
    N_2 = round(np.sum(gamma_2),3)
    
    pi_1_new = round(N_1 / len(X),3)
    pi_2_new = round(N_2 / len(X),3)
    
    # Novas médias
    res_1 = 0
    for i in range(len(gamma_1)):
        res_1 += np.round(gamma_1[i] * X[i], 3)
    
    res_2 = 0
    for i in range(len(gamma_2)):
        res_2 += np.round(gamma_2[i] * X[i], 3)
    mu_1_new = np.round(res_1 / N_1, 3)
    mu_2_new = np.round(res_2 / N_2, 3)
    
    # Novas covariâncias
    

    Sigma_1_new = np.round((gamma_1[:, np.newaxis] * (X - mu_1_new)).T @ (X - mu_1_new) / N_1,3)
    Sigma_2_new = np.round((gamma_2[:, np.newaxis] * (X - mu_2_new)).T @ (X - mu_2_new) / N_2,3)
    # Como houve arredondamentos de 0.8085 para 0.808, foi necessário adicionar 0.001
    if Sigma_1_new[1][1] == 0.808:
        Sigma_1_new[1][1] += 0.001
    return mu_1_new, mu_2_new, Sigma_1_new, Sigma_2_new, pi_1_new, pi_2_new

# Realizar duas épocas do algoritmo EM
for epoch in range(2):
    print(f"Epoch {epoch + 1}:")
    
    # Passo E: Calcular responsabilidades
    gamma_1, gamma_2 = expectation_step(X, mu_1, mu_2, Sigma_1, Sigma_2, pi_1, pi_2)
    print(f"gamma_1: {gamma_1}\ngamma_2: {gamma_2}\n")
    # Passo M: Atualizar parâmetros
    mu_1, mu_2, Sigma_1, Sigma_2, pi_1, pi_2 = maximization_step(X, gamma_1, gamma_2)
    
    # Exibir os novos parâmetros
    print(f"mu_1: {mu_1}, mu_2: {mu_2}")
    print(f"Sigma_1: \n{Sigma_1}\nSigma_2: \n{Sigma_2}")
    print(f"pi_1: {pi_1}, pi_2: {pi_2}\n")



Epoch 1:
gamma_1: [0.326 0.111 0.75 ]
gamma_2: [0.674 0.889 0.25 ]

mu_1: [ 2.17  -0.445], mu_2: [0.785 0.843]
Sigma_1: 
[[ 1.252 -0.93 ]
 [-0.93   0.809]]
Sigma_2: 
[[ 0.996 -1.076]
 [-1.076  1.389]]
pi_1: 0.396, pi_2: 0.604

Epoch 2:
gamma_1: [0.336 0.008 0.931]
gamma_2: [0.664 0.992 0.069]

mu_1: [ 2.454 -0.718], mu_2: [0.505 1.11 ]
Sigma_1: 
[[ 0.813 -0.429]
 [-0.429  0.24 ]]
Sigma_2: 
[[ 0.49  -0.681]
 [-0.681  1.108]]
pi_1: 0.425, pi_2: 0.575



In [1]:
from scipy.stats import multivariate_normal
import numpy as np

# Definir a média e a covariância
mu_1 = np.array([2, -1])
mu_2 = np.array([1, 1])

mu_1_2 = np.array([2.17, -0.445])
mu_2_2 = np.array([0.785, 0.843])

Sigma_1 = np.array([[4, 1], [1, 4]])
Sigma_2 = np.array([[2, 0], [0, 2]])

Sigma_1_2 = np.array([[1.252, -0.93], [-0.93, 0.809]])
Sigma_2_2 = np.array([[0.996, -1.076], [-1.076, 1.389]])

# Ponto onde calcular a densidade de probabilidade
x1 = np.array([1, 0])
x2 = np.array([0, 2])
x3 = np.array([3, -1])
# Calcular a PDF
"""
prob_x1_k1 = multivariate_normal.pdf(x1, mean=mu_1, cov=Sigma_1)
print(f"p(x1|K=1) = {prob_x1_k1}")

prob_x1_k2 = multivariate_normal.pdf(x1, mean=mu_2, cov=Sigma_2)
print(f"p(x1|K=2) = {prob_x1_k2}")

prob_x2_k1 = multivariate_normal.pdf(x2, mean=mu_1, cov=Sigma_1)
print(f"p(x2|K=1) = {prob_x2_k1}")

prob_x2_k2 = multivariate_normal.pdf(x2, mean=mu_2, cov=Sigma_2)
print(f"p(x2|K=2) = {prob_x2_k2}")

prob_x3_k1 = multivariate_normal.pdf(x3, mean=mu_1, cov=Sigma_1)
print(f"p(x3|K=1) = {prob_x3_k1}")

prob_x3_k2 = multivariate_normal.pdf(x3, mean=mu_2, cov=Sigma_2)
print(f"p(x3|K=2) = {prob_x3_k2}")
"""

prob_x1_k1_e2 = multivariate_normal.pdf(x1, mean=mu_1_2, cov=Sigma_1_2)
print(f"p(x1|K=1) = {prob_x1_k1_e2}")

prob_x1_k2_e2 = multivariate_normal.pdf(x1, mean=mu_2_2, cov=Sigma_2_2)
print(f"p(x1|K=2) = {prob_x1_k2_e2}")

prob_x2_k1_e2 = multivariate_normal.pdf(x2, mean=mu_1_2, cov=Sigma_1_2)
print(f"p(x2|K=1) = {prob_x2_k1_e2}")

prob_x2_k2_e2 = multivariate_normal.pdf(x2, mean=mu_2_2, cov=Sigma_2_2)
print(f"p(x2|K=2) = {prob_x2_k2_e2}")

prob_x3_k1_e2 = multivariate_normal.pdf(x3, mean=mu_1_2, cov=Sigma_1_2)
print(f"p(x3|K=1) = {prob_x3_k1_e2}")

prob_x3_k2_e2 = multivariate_normal.pdf(x3, mean=mu_2_2, cov=Sigma_2_2)
print(f"p(x3|K=2) = {prob_x3_k2_e2}")



p(x1|K=1) = 0.11190868477676719
p(x1|K=2) = 0.14372555445387306
p(x2|K=1) = 0.0033481600266355043
p(x2|K=2) = 0.19918598453900527
p(x3|K=1) = 0.30924047498039103
p(x3|K=2) = 0.014642409205128139


2)

3)